name: Go

on:
  push:
    branches: [ main, fix-test ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-20.04 # explicitly use 20.04, see commit 428c40018a
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        go-version: ["1.20.x"]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: |
        make cross qemu-wrapper vm win-gvproxy win-sshproxy
        mv bin/gvproxy.exe bin/gvproxy-windowsgui.exe

    - uses: actions/upload-artifact@v3
      with:
        name: gvisor-tap-vsock-binaries
        path: bin/*

  tests:
    runs-on: macos-latest # Only Mac runners support nested virt
    needs: build # Don't bother testing if cross arch build fails
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3

    - name: Install
      run: |
        brew install qemu
        touch continue

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.x

    - name: Test DNS
      run: nslookup -query=srv _ldap._tcp.google.com

    - name: Test
      run: make test

    - name: Test DNS 2
      run: nslookup -query=srv _ldap._tcp.google.com

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: files
        path: | 
          test/qcon.log
          test/capture.pcap


  win-sshproxy-tests:
    runs-on: windows-latest # Only builds/runs on windows
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.x

    - name: Build 
      run: make win-sshproxy

    - name: Test 
      run: go test -v .\test-win-sshproxy


